using AM.TribonAutomationProbe.Core;
using Xunit;

namespace AM.TribonAutomationProbe.Tests;
public sealed class GeometryLabelMatcherTests
{
    private static T Read<T>(string n) => System.Text.Json.JsonSerializer.Deserialize<T>(File.ReadAllText(Path.Combine(AppContext.BaseDirectory,"Fixtures","GeometryObjectPoc",n)),JsonDefaults.Options)!;
    private static DetectedGeometryObject Object(string id) => new(id, GeometryObjectCategory.LIFTING_BEAM, "high", new(0,0,10,10), new[] { id+"-s" }, new[] { id+"-g" }, 1, new(1));
    private static GeometryObjectDisplayIdMap Ids(params string[] ids) => new(ids.Select((x,i) => new GeometryObjectDisplayIdentity(x, GeometryObjectCategory.LIFTING_BEAM, "LB-"+(i+1).ToString("00"))).ToArray());
    [Fact] public void MatchedDuplicateConflictAndUnrelatedTextsHaveStableSemantics() { var o = new[] { Object("A"), Object("B"), Object("C") }; var ids = Ids("A","B","C"); var labels = new[] { new ExistingGeometryLabel("1","LB-01",new(0,12,2,14)), new ExistingGeometryLabel("2","LB-02",new(0,12,2,14)), new ExistingGeometryLabel("3","LB-02",new(4,12,6,14)), new ExistingGeometryLabel("4","LB-03",new(100,100,102,102)), new ExistingGeometryLabel("5","NOTE",new(1,1,2,2)) }; var r = GeometryObjectLabelMatcher.MatchResult(o, ids, labels); Assert.Equal(1, r.Matches.Count(x=>x.Status==GeometryLabelMatchStatus.Matched)); Assert.Equal(1, r.Matches.Count(x=>x.Status==GeometryLabelMatchStatus.Duplicate)); Assert.Equal(1, r.Matches.Count(x=>x.Status==GeometryLabelMatchStatus.TextConflict)); Assert.Contains(r.OtherTexts, x=>x.RuntimeHandle=="2"); Assert.Contains(r.OtherTexts, x=>x.RuntimeHandle=="3"); Assert.Contains(r.OtherTexts, x=>x.RuntimeHandle=="4"); Assert.Contains(r.OtherTexts, x=>x.RuntimeHandle=="5"); }
    [Fact] public void InvalidOptionsAndDisplayMapAreStructuredFailures() { var o = new[] { Object("A") }; var ex = Assert.Throws<ProbeException>(() => GeometryObjectLabelMatcher.Match(o, Ids("A"), Array.Empty<ExistingGeometryLabel>(), new(-1, .5, 1))); Assert.Equal(ProbeErrorCodes.InvalidMessage, ex.Code); var missing = new GeometryObjectDisplayIdMap(Array.Empty<GeometryObjectDisplayIdentity>()); ex = Assert.Throws<ProbeException>(() => GeometryObjectLabelMatcher.Match(o, missing, Array.Empty<ExistingGeometryLabel>())); Assert.Equal("validation", ex.Category); }
    [Fact] public void MinimumMaximumAndNonFiniteOptionsAreRejected() { var o=new[]{Object("A")}; foreach(var x in new[]{new GeometryLabelMatchOptions(double.NaN),new GeometryLabelMatchOptions(double.PositiveInfinity),new GeometryLabelMatchOptions(-1),new GeometryLabelMatchOptions(10,.5,5)}) { var ex=Assert.Throws<ProbeException>(()=>GeometryObjectLabelMatcher.Match(o,Ids("A"),Array.Empty<ExistingGeometryLabel>(),x)); Assert.Equal(ProbeErrorCodes.InvalidMessage,ex.Code); } }
    [Fact] public void FormalBeforeAndAfterHaveTwelveUniqueMatches() { var d=Read<GeometryObjectDetectionResponse>("geometry-detection.formal.json"); var ids=GeometryObjectDisplayIdAssigner.Assign(d.Objects); foreach(var n in new[]{"geometry-labels-before.formal.json","geometry-labels-after.formal.json"}) { var l=Read<GeometryLabelInspectionResponse>(n); var r=GeometryObjectLabelMatcher.MatchResult(d.Objects,ids,l.Labels); Assert.Equal(12,r.Matches.Count); Assert.All(r.Matches,x=>Assert.Equal(GeometryLabelMatchStatus.Matched,x.Status)); Assert.Empty(r.OtherTexts); } }
}
