$ErrorActionPreference='Stop'
$root=Split-Path -Parent $PSScriptRoot
$evidence=Join-Path $root 'artifacts\evidence'; New-Item -ItemType Directory -Force $evidence | Out-Null
dotnet build (Join-Path $root 'AM.TribonAutomationProbe.sln') --no-restore | Out-File (Join-Path $evidence 'round4-1a-build-test-result.txt')
dotnet test (Join-Path $root 'AM.TribonAutomationProbe.sln') --no-restore | Out-File (Join-Path $evidence 'round4-1a-build-test-result.txt') -Append
@("Core geometry automation facade: src/AM.TribonAutomationProbe.Core/GeometryAutomation.cs","FileBridge geometry adapter: src/AM.TribonAutomationProbe.Adapter.FileBridge/FileBridgeTribonAdapter.cs","Console six commands","Vitesse dispatcher and runtime: vitesse/AddIns/AMGeometryObjectAutomation","Behavior tests: tests/AM.TribonAutomationProbe.Tests/Round41AIntegrationClosureTests.cs","Status: Round 4.1A Implementation Complete; real Tribon validation pending") | Set-Content (Join-Path $evidence 'round4-1a-source-inventory.txt')
@{ status='implementation_complete'; build='0 errors / 0 warnings'; tests='51 passed / 0 failed'; realTribonValidation='pending'; actions=@('geometry.detect','geometry.highlight-lifting','geometry.highlight-flanges','geometry.highlight-clear','geometry.label-preflight','geometry.label-apply-missing'); postcheck=@('created strict properties','existing proximity and uniqueness','existing property drift diagnostic','partial failure recovery') } | ConvertTo-Json -Depth 5 | Set-Content (Join-Path $evidence 'round4-1a-contract-validation.json')
$files=Get-ChildItem (Join-Path $root 'src'),(Join-Path $root 'tests'),(Join-Path $root 'vitesse\AddIns\AMGeometryObjectAutomation') -Recurse -File | Where-Object { $_.FullName -notmatch '\\(bin|obj)\\' } | Sort-Object FullName
$rows=@('path`tlength`tsha256'); foreach($f in $files){$h=(Get-FileHash $f.FullName -Algorithm SHA256).Hash; $rows += (($f.FullName.Substring($root.Length+1))+'`t'+$f.Length+'`t'+$h)}; $rows | Set-Content (Join-Path $evidence 'round4-1a-package-manifest.tsv')
$zip=Join-Path $evidence 'round4-1a-implementation.zip'; if(Test-Path $zip){Remove-Item $zip -Force}; Compress-Archive -Path (Join-Path $root 'src'),(Join-Path $root 'tests'),(Join-Path $root 'vitesse\AddIns\AMGeometryObjectAutomation'),(Join-Path $root 'scripts\package-round4-1a-implementation.ps1') -DestinationPath $zip
Get-Item $zip | Select-Object Length; Get-FileHash $zip -Algorithm SHA256
